### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by wowbagger84** [Nrjwolf/unity-shader-smooth-radial-gradient#1]
Is it possible to get this working with transparency? I would like to use this to create a vignette effect in my game, but since it only seems to work with solid colors, it's not very useful.

**Comment by Nrjwolf** [comment]
Hi, added Blend mode. Try it now. 

Also, for vignette you can use unity post process https://learn.unity.com/tutorial/post-processing-effects-vignette

**Comment by wowbagger84** [comment]
Awesome fix! Trying to avoid post-processing (mobile project) Will add your name to contributions :)
